name: App-down

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: "GHCR Push: Build and push Docker image"
        uses: Its4Nik/NGX-action@internal
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          dockerfile-path: ./dockerfiles/
          build-context: Dockerfile_app-down
          build-only: false
